services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=raw_trades'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
