server:
  port: 8082
  
spring:
  application:
    name: trade-system-consumer

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: trade-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: com.kiddieopt.trade_system_consumer.model
